Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "docker" do |d|
    d.pull_images "nginx"
    d.pull_images "httpd"
    d.pull_images "n43jl/executor"
  end
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.ssh.insert_key = false
end

