Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
  end
  config.vm.box = "docker-update"
  config.vm.network "forwarded_port", guest: 8000, host: 8000
end

