Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 6144
    v.cpus = 8
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "docker" do |d|
    d.run "n43jl/docker-set",
      args: "-it --privileged --name=docker-set"
    config.vm.provision :shell, path: "bootstrap.sh"
  end
  config.vm.network "forwarded_port", guest: 2376, host: 5000
end

